Update create_release.yml

diff --git a/.github/workflows/create_release.yml b/.github/workflows/create_release.yml
--- a/.github/workflows/create_release.yml
+++ b/.github/workflows/create_release.yml
@@ -49,8 +49,10 @@ jobs:
         id: current_version
         run: echo "str=${{ steps.slicer_version.outputs.slicer_version }}:${{ steps.profile_version.outputs.config_version }}" >> $GITHUB_OUTPUT
       - name: test version
-        run: exit 1
-        if: ${{ steps.current_version.outputs.str}} == ${{ steps.get-latest-tag.outputs.tag }}
+        run: |
+          echo "Error: the version already exists"
+          exit 1
+        if: ${{ steps.current_version.outputs.str == steps.get-latest-tag.outputs.tag }}
       - name: Create tag
         run: echo "TODO:create tag"
 #      - name: Create tag
